### ISSUE TITLE
cannot import on python 3.10

### ISSUE THREAD

**Issue by CRCGlobal** [git-albertomarin/badX12#210]
* badX12 version: 0.2.2
* Python version: 3.10
* Operating System:

### Description
```
 import badx12
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python310\lib\site-packages\badx12\__init__.py", line 6, in <module>
    from .__main__ import cli
  File "C:\Python310\lib\site-packages\badx12\__main__.py", line 10, in <module>
    from .common.click import add_commands
  File "C:\Python310\lib\site-packages\badx12\common\click.py", line 2, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (C:\Python310\lib\collections\__init__.py)
```
The Iterable abstract class was removed from collections in Python 3.10. See the deprecation note in the 3.9 [collections docs](https://docs.python.org/3.9/library/collections.html). In the section [Removed](https://docs.python.org/3/whatsnew/3.10.html#removed) of the 3.10 docs, the item
``
Remove deprecated aliases to [Collections Abstract Base Classes](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes) from the collections module. (Contributed by Victor Stinner in bpo-37324.)

**Comment by jvigilan** [comment]
can change "from collections import Iterable" to "from collections.abc import Iterable" and it will work again...

**Comment by cdellafera** [comment]
Why does "pip install -U badx12" still install the version with the deprecated aliases?
