### ISSUE TITLE
Error when running badx12 from command line

### ISSUE THREAD

**Issue by sattuchin** [git-albertomarin/badX12#79]
* badX12 version: master branch
* Python version: 2.7
* Operating System: Ubuntu 18.04

### Description

I tried converting edi files to json via command line, as documented. However, badx12 gave my an error.

### What I Did

```
cd ~/files/badx12
badx12 parse "./1.edi"

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/badx12", line 7, in <module>
    from badx12.__main__ import cli
  File "/home/ubuntu/.local/lib/python2.7/site-packages/badx12/__init__.py", line 4, in <module>
    from .document import EDIDocument
  File "/home/ubuntu/.local/lib/python2.7/site-packages/badx12/document.py", line 3, in <module>
    from badx12.utils import Interchange
  File "/home/ubuntu/.local/lib/python2.7/site-packages/badx12/utils/__init__.py", line 1, in <module>
    from .element import Element
  File "/home/ubuntu/.local/lib/python2.7/site-packages/badx12/utils/element.py", line 41
    msg=f"Field {self.name} is too short. Found {content_length} characters, expected "
                                                                                      ^
SyntaxError: invalid syntax
```

**Comment by albmarin** [comment]
@sattuchin Python2.7 is not supported. badX12 requires Python3.6 or higher.

**Comment by lft-arjun** [comment]
I am also facing same issue but @sattuchin does this package available for pip3? I notice only pip installation is available in docs.
